// REDUCER ===> NOTES
export const LOAD_NOTES = "LOAD_NOTES";
export const ADD_NOTE = "ADD_NOTE";
export const CANCEL_ADDING_NEW_NOTE = "CANCEL_ADDING_NEW_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const COPY_NOTE = "COPY_NOTE";
export const REFRESH_NOTES_ID = "REFRESH_NOTES_ID";

export const CHANGE_NOTE_LABELS = "CHANGE_NOTE_LABELS";
export const REFRESH_NOTES_LABELS_NAMES = "REFRESH_NOTES_LABELS_NAMES";
export const DELETE_LABEL_FROM_NOTES = "DELETE_LABEL_FROM_NOTES";

// REDUCER ===> LABELS
export const LOAD_LABELS = "LOAD_LABELS";
export const ADD_LABEL = "ADD_LABEL";
export const RENAME_LABEL = "RENAME_LABEL";
export const REMOVE_LABEL = "REMOVE_LABEL";

// REDUCER ===> EDITING
export const START_EDITING = "START_EDITING";
export const EDIT_NOTE = "EDIT_NOTE";
export const CHANGE_COLOR = "CHANGE_COLOR";
export const CLOSE_EDIT_MODE = "CLOSE_EDIT_MODE";
export const DATA_CHANGE = "DATA_CHANGE";
