// REDUCER ===> SERVER_DATA
export const LOAD_SERVER_DATA = "LOAD_SERVER_DATA";
export const SAVE_DATA_TO_SERVER = "SAVE_DATA_TO_SERVER";

// REDUCER ===> NOTES
export const LOAD_NOTES_FROM_SERVER = "LOAD_NOTES_FROM_SERVER";
export const ADD_NOTE = "ADD_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const COPY_NOTE = "COPY_NOTE";
export const REFRESH_NOTES_ID = "REFRESH_NOTES_ID";

export const ADD_LABELS_TO_NOTE = "ADD_LABELS_TO_NOTE";
export const REMOVE_LABELS_TO_NOTE = "REMOVE_LABELS_TO_NOTE";
export const REFRESH_NOTES_LABELS_NAMES = "REFRESH_NOTES_LABELS_NAMES";

// REDUCER ===> LABELS
export const LOAD_LABELS_FROM_SERVER = "LOAD_LABELS_FROM_SERVER";
export const OPEN_LABELS_MANAGER = "OPEN_LABELS_MANAGER";
export const ADD_LABEL = "ADD_LABEL";
export const RENAME_LABEL = "RENAME_LABEL";
export const REMOVE_LABEL = "REMOVE_LABEL";

// REDUCER ===> EDITING
export const START_EDITING = "START_EDITING";
export const EDIT_NOTE = "EDIT_NOTE";
export const CHANGE_COLOR = "CHANGE_COLOR";
export const CLOSE_EDIT_MODE = "CLOSE_EDIT_MODE";
